/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `application`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://packages.confluent.io/maven/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.duckdb.duckdb.jdbc)
    api(libs.sqlline.sqlline)
    api(libs.org.apache.kafka.kafka.clients)
    api(libs.io.confluent.kafka.schema.registry.client)
    api(libs.io.confluent.kafka.avro.serializer)
    api(libs.io.confluent.kafka.json.schema.serializer)
    api(libs.io.confluent.kafka.protobuf.serializer)
    api(libs.io.confluent.kafka.protobuf.types)
    api(libs.io.confluent.kafka.schema.registry.client.encryption)
    api(libs.io.confluent.kafka.schema.registry.client.encryption.aws)
    api(libs.io.confluent.kafka.schema.registry.client.encryption.azure)
    api(libs.io.confluent.kafka.schema.registry.client.encryption.gcp)
    api(libs.io.confluent.kafka.schema.registry.client.encryption.hcvault)
    api(libs.io.confluent.kafka.schema.registry.client.encryption.tink)
    api(libs.io.confluent.kafka.schema.rules)
    api(libs.com.google.api.grpc.proto.google.common.protos)
    api(libs.io.kcache.kcache)
    api(libs.io.kcache.kcache.caffeine)
    api(libs.com.google.guava.guava)
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.csv)
    api(libs.org.slf4j.slf4j.api)
    api(libs.org.slf4j.slf4j.log4j12)
    api(libs.info.picocli.picocli)
    api(libs.io.vavr.vavr)
    api(libs.io.reactivex.rxjava3.rxjava)
    api(libs.com.esotericsoftware.kryo)
    api(libs.com.google.protobuf.protobuf.java)
    api(libs.com.squareup.wire.wire.schema.jvm)
    api(libs.javax.xml.bind.jaxb.api)
    testImplementation(libs.io.confluent.kafka.schema.registry)
    testImplementation(libs.org.apache.kafka.kafka.clients)
    testImplementation(variantOf(libs.org.apache.kafka.kafka.clients) { classifier("test") })
    testImplementation(libs.org.apache.kafka.kafka.v2.v13)
    testImplementation(variantOf(libs.org.apache.kafka.kafka.v2.v13) { classifier("test") })
    testImplementation(libs.org.apache.kafka.kafka.server)
    testImplementation(libs.org.apache.kafka.kafka.server.common)
    testImplementation(variantOf(libs.org.apache.kafka.kafka.server.common) { classifier("test") })
    testImplementation(libs.org.apache.kafka.kafka.raft)
    testImplementation(libs.org.apache.kafka.kafka.storage)
    testImplementation(libs.org.apache.kafka.kafka.group.coordinator)
    testImplementation(libs.org.scala.lang.scala.library)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.params)
    testImplementation(libs.org.openjdk.jmh.jmh.core)
    testImplementation(libs.org.openjdk.jmh.jmh.generator.annprocess)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // TODO: find way to update to 3.x version of caffeine, but for now we need to stick with 2.x
    // Force Gradle to use the 2.x version that kcache requires
    implementation("com.github.ben-manes.caffeine:caffeine") {
        version {
            strictly("2.9.3")
        }
    }
}

group = "io.kcache"
version = "2.1.0"
description = "omni-kwack"
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    applicationName = "omni-kwack"
    mainClass.set("io.kcache.kwack.KwackMain") 
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType<Test> {
    useJUnitPlatform() 
    
    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.register<JavaExec>("runAvroBenchmark") {
    group = "benchmark"
    description = "Runs the Kwack Avro Read Benchmark"
    classpath = sourceSets.test.get().runtimeClasspath
    mainClass.set("io.kcache.kwack.KwackAvroReadBenchmark")
    // Allow passing arbitrary arguments to the benchmark main class
    // e.g., ./gradlew runAvroBenchmark -Pexec.args="-p recordCount=1000"
    if (project.hasProperty("exec.args")) {
        args((project.property("exec.args") as String).split(" "))
    }
}
